stages:
  - prepare
  - build

variables:
  REGISTRY_URL: "harbor.wangwei.devopscamp.us"
  REGISTRY_PROJECT: "vote"

prepare:
  stage: prepare
  image: alpine:latest
  before_script:
    - apk add --update git bash
  script:
    - |
      echo '
      changed_dirs=()
      for dir in */
      do
        dir=${dir%*/}
        if ! git diff --quiet HEAD^ HEAD -- "./$dir"
        then
          changed_dirs+=("$dir")
        fi
      done
      json_output="{\"path\":["
      for (( i=0; i<${#changed_dirs[@]}; i++ ));
      do
          json_output+="{\"name\":\"${changed_dirs[$i]}\"}"
          if (( i < ${#changed_dirs[@]}-1 )); then
              json_output+=","
          fi
      done
      json_output+="]}"
      echo $json_output > changed_dirs.json
      ' > /tmp/script.sh
    - chmod +x /tmp/script.sh
    - bash /tmp/script.sh
  artifacts:
    paths:
      - changed_dirs.json

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - |
      apk add --no-cache jq
      changed_dirs=$(jq -r '.path[].name' changed_dirs.json)
      for dir in $changed_dirs
      do
        if [ -f "./${dir}/Dockerfile" ]
        then
          echo "${DOCKER_PASSWORD}" | docker login $REGISTRY_URL -u $DOCKER_USERNAME --password-stdin
          docker build -t $REGISTRY_URL/$REGISTRY_PROJECT/$dir:${CI_COMMIT_SHA} ./$dir
          docker push $REGISTRY_URL/$REGISTRY_PROJECT/$dir:${CI_COMMIT_SHA}
        fi
      done
  dependencies:
    - prepare
