# name: Hello World

# on:
#   push:
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Run script
#         run: |
#           ls -al
