# name: Docker Build

# on:
#   push:

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     env:
#       REGISTRY_URL: "harbor.wangwei.devopscamp.us"
#       REGISTRY_PROJECT: "vote"

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Check changes in directories
#         id: dir_changes
#         run: |
#           for dir in */
#           do
#             dir=${dir%*/}
#             if git diff --quiet HEAD^ HEAD -- ./$dir
#             then
#               echo "$dir: false" >> changed_dirs.txt
#             else
#               echo "$dir: true" >> changed_dirs.txt
#             fi
#           done
#           cat changed_dirs.txt

#       - name: Build Docker images
#         run: |
#           echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ env.REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#           while IFS= read -r line
#           do
#             dir=$(echo $line | cut -d ':' -f 1)
#             changed=$(echo $line | cut -d ' ' -f 2)
#             if [ "$changed" == "true" ] && [ -f "./$dir/Dockerfile" ]
#             then
#               docker build -t ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_PROJECT }}/$dir:${{ github.sha }} ./$dir
#               docker push ${{ env.REGISTRY_URL }}/${{ env.REGISTRY_PROJECT }}/$dir:${{ github.sha }}
#             fi
#           done < changed_dirs.txt
